# Generated by Django 5.0.4 on 2025-12-26 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/')),
                ('description', models.TextField(blank=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Designate if this is the central Student Union admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text Announcement')], max_length=10)),
                ('author_name', models.CharField(help_text='Individual name or credit', max_length=100)),
                ('duration', models.IntegerField(default=10, help_text='Duration in seconds')),
                ('is_urgent', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/%Y/%m/%d/')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved / Live'), ('scheduled', 'Scheduled'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notices.club')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
