# Generated by Django 5.0.4 on 2025-12-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='department',
            field=models.CharField(blank=True, help_text='Specific department or faculty', max_length=100),
        ),
    ]
